[package]
name = "tokenization"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.fm)"]

[dependencies]
share = { git = "https://github.com/unconfirmedlabs/share.git", rev = "2523faa247727460d36b24af0e580457baa22000" }
receipt_fixture = { local = "fixtures/receipt", modes = ["test"] }
