[package]
name = "tokenization"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.fm)"]

[dependencies]
share = { git = "https://github.com/unconfirmedlabs/share.git", rev = "96d443bf7c84c1870f269507ff1c35f009345abb" }
receipt_fixture = { local = "fixtures/receipt", modes = ["test"] }
